# Generated by Django 5.2.1 on 2025-06-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_book_description_publisher_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="country",
            field=models.CharField(default="USA", max_length=50),
        ),
    ]
