# Generated by Django 5.2.1 on 2025-06-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_publisher_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
    ]
